export const FETCH_LIST_PRODUCT_REQUEST =
  "@@productReducer/FETCH_LIST_PRODUCT_REQUEST";
export const FETCH_LIST_PRODUCT_SUCCESS =
  "@@productReducer/FETCH_LIST_PRODUCT_SUCCESS";
export const FETCH_LIST_PRODUCT_FAIL =
  "@@productReducer/FETCH_LIST_PRODUCT_FAIL";
